{% set name = "lightlda" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  git_url: https://github.com/Karthikmvd/LightLDA.git

build:
  number: 0
  script:  sh build.sh

requirements:
  build:
    - python
 
  run:
    - python
   

#test:
#  imports:
#    - lightlda

about:
  home: https://github.com/Microsoft/LightLDA
  summary: 'LightLDA is a gradient boosting framework that uses tree based learning algorithms.'

  description: |
    A fast, distributed, high performance gradient boosting (GBDT, GBRT, GBM or MART) framework based on decision tree algorithms, used for ranking, classification and many other machine learning tasks.

  dev_url: https://github.com/Microsoft/LightLDA

extra:
  recipe-maintainers:
    - none
